"""SimpleX Chat — Python client library for chat bots."""

from . import util as util  # re-export the util namespace
from ._version import __version__
from .api import (
    ChatApi,
    ChatCommandError,
    ConnReqType,
    ContactAlreadyExistsError,
    Db,
    PostgresDb,
    SqliteDb,
)
from .bot import (
    Bot,
    BotCommand,
    BotProfile,
    ChatMessage,
    Client,
    CommandHandler,
    EventHandler,
    FileMessage,
    ImageMessage,
    LinkMessage,
    Message,
    MessageHandler,
    Middleware,
    ParsedCommand,
    Profile,
    ReportMessage,
    TextMessage,
    UnknownMessage,
    VideoMessage,
    VoiceMessage,
)
from .core import ChatAPIError, ChatError, ChatInitError, CryptoArgs, MigrationConfirmation

__all__ = [
    "Bot",
    "BotCommand",
    "BotProfile",
    "ChatAPIError",
    "ChatApi",
    "ChatCommandError",
    "ChatError",
    "ChatInitError",
    "ChatMessage",
    "Client",
    "CommandHandler",
    "ConnReqType",
    "ContactAlreadyExistsError",
    "CryptoArgs",
    "Db",
    "EventHandler",
    "FileMessage",
    "ImageMessage",
    "LinkMessage",
    "Message",
    "MessageHandler",
    "Middleware",
    "MigrationConfirmation",
    "ParsedCommand",
    "PostgresDb",
    "Profile",
    "ReportMessage",
    "SqliteDb",
    "TextMessage",
    "UnknownMessage",
    "VideoMessage",
    "VoiceMessage",
    "__version__",
    "util",
]
