name: simplex-chat
version: 0.4.0
#synopsis:
#description:
homepage: https://github.com/simplex-chat/simplex-chat#readme
license: AGPL-3
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: Web, System, Services, Cryptography
extra-source-files:
  - README.md

dependencies:
  - aeson == 1.5.*
  - ansi-terminal == 0.10.*
  - attoparsec == 0.13.*
  - base >= 4.7 && < 5
  - base64-bytestring >= 1.0 && < 1.3
  - bytestring == 0.10.*
  - composition == 1.0.*
  - containers == 0.6.*
  - cryptonite >= 0.27 && < 0.30
  - directory == 1.3.*
  - exceptions == 0.10.*
  - file-embed == 0.0.14.*
  - filepath == 1.4.*
  - mtl == 2.2.*
  - optparse-applicative == 0.15.*
  - process == 1.6.*
  - simple-logger == 0.1.*
  - simplexmq == 0.4.*
  - sqlite-simple == 0.4.*
  - stm == 2.5.*
  - terminal == 0.2.*
  - text == 1.2.*
  - time == 1.9.*
  - unliftio == 0.2.*
  - unliftio-core == 0.2.*

library:
  source-dirs: src

executables:
  simplex-chat:
    source-dirs: apps/simplex-chat
    main: Main.hs
    dependencies:
      - simplex-chat
    ghc-options:
      - -threaded

tests:
  simplex-chat-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - simplex-chat
      - async == 2.2.*
      - hspec == 2.7.*
      - network == 3.1.*
      - stm == 2.5.*

ghc-options:
  # - -haddock
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
