sequenceDiagram
  participant B as Bob (sender)
  participant S as server (queue RID)
  participant A as Alice (recipient)

  note over A: creating queue<br>("public" key RK<br>for msg retrieval)
  A ->> S: 1. create queue ("NEW")
  S ->> A: respond with queue RID and SID ("IDS")

  note over A: out-of-band msg<br>(sender's queue SID<br>and "public" key EK<br>to encrypt msgs)
  A -->> B: 2. send out-of-band message

  note over B: confirm queue<br>("public" key SK for<br>sending messages<br>and any optional<br>info encrypted with<br>"public" key EK)
  B ->> S: 3. confirm queue ("SEND" command not signed)

  S ->> A: 4. deliver Bob's message
  note over A: decrypt message<br>("private" key EK)
  A ->> S: 5. secure queue ("KEY", RK-signed)

  note over S: 6. simplex<br>queue RID<br>is ready to use!
