sequenceDiagram
  participant B as Bob (sender)
  participant S as server (queue RID)
  participant A as Alice (recipient)

  note over B: encrypt message<br>("public" key EK)
  B ->> S: 1. send message to SID (SK-signed command)

  S ->> A: 2. receive messages from RID (RK-signed subscription)
  note over A: decrypt message<br>("private" key EK)
