graph LR
  VS{{"verify sender (SK)"}}
  VR{{"verify recipient (RK)"}}

  S(sender) -->|msg| VS
  subgraph "server (queue RID, SID)"
    VS --> DB[("storage")]
    DB --> VR
  end
  R(recipient) -->|"1) sub"| VR
  VR -->|"2) msg"| R
