name: Question
description: Ask your question
title: "[Q]: "
labels: ["question", "triage"]
body:
- type: markdown
  attributes:
    value: |
      Generally, we encourage you to ask questions via our [SimpleX address](https://smp6.simplex.im/a#lrdvu2d8A1GumSmoKb2krQmtKhWXq-tyGpHuM7aMwsw), but you can do it anyway :)
- type: textarea
  attributes:
    label: Question
    description: Please ask your question in plain english.
    placeholder: Is SimpleX - chat?
  validations:
    required: true
