sequenceDiagram
  participant B as Bob (sender)
  participant S as server (conn. ID)
  participant A as Alice (recipient)

  note over B: encrypt message <br> ("public" key EK)
  B ->> S: 1. send message (SK-signed req)

  S ->> A: 2. retrieve messages (RK-signed req)
  note over A: decrypt message <br> ("private" key EK)
