// The names board: what each frame shows, where it sits, and the arrow that reaches it.
// A frame's key is its tag on the board; `screen` names the mockup in screens.js when they differ.

export const TITLE = "SimpleX names - every screen, on the web and where it meets the app";
export const SUBTITLE =
  "one tree per surface, left to right - blue is the normal path, orange a variant or a failure, grey a platform difference, " +
  "and dashed is everything that crosses between the site and the app";
export const CORNER = ["plans/names-codes/names-flow.svg", "generated by mockups/board.mjs"];

const HOST = "store.simplex.chat";
const ORDER = `${HOST}/?order=q7ZpL2dN9xWc4KfR8tYb1A`;

export const SECTIONS = [
  {
    title: "On the web",
    note: `${HOST} - the badge site, one build: a name is bought through the badge checkout and its payment screens`,
    rows: [
      { label: "Buying a name, start to finish", kind: "desktop", cells: ["N0", "N1", "N1a", "N1b", "N2", "N3", "N5", "N6", "N4"] },
      { label: "What the name check can answer instead", kind: "desktop", cells: [null, "N1c", "N1d", "N1e", "N1f", "N1g", "N1h"] },
      { label: "The term at its edges", kind: "desktop", cells: [null, null, null, null, "N2a", "N2b"] },
    ],
  },
  {
    title: "Where it meets the app",
    note: "drawn after canvas 5g, built by #7530 and not here",
    rows: [{ label: "The code goes to the app in the link", kind: "app", cells: [null, null, null, null, null, null, null, "A1", "A1a"] }],
  },
  {
    title: "Refused at checkout",
    note: "the badge checkout's refusals, with the name's summary",
    rows: [{ label: "POST /api/invoice says no", kind: "desktop", cells: [null, null, null, null, "N3a", "N3b", "N3c", "N3d", "N3e"] }],
  },
  {
    title: "The other ways a payment ends",
    note: "shared with badges: nothing about these screens depends on what is being bought",
    rows: [
      { label: "Paying in Bitcoin or Monero", kind: "desktop", cells: [null, null, null, null, null, "N5a", "N5b", "N7a", "N7b"] },
      { label: "Paying by card", kind: "desktop", cells: [null, null, null, null, null, "N8", "N8a", "N8b", "N8c"] },
      { label: "A code this browser cannot show, and a link to nothing", kind: "desktop", cells: [null, null, null, null, null, null, "N4a", "N4b", "N9"] },
    ],
  },
  {
    title: "Your codes, and the dark theme",
    note: "the history list holds badges and names side by side; four screens shown again in the dark palette",
    rows: [{ label: "History, then the same screens dark", kind: "desktop", cells: ["N10", null, "D0", "D1b", "D3", "D4"] }],
  },
  {
    title: "On the web, on a phone",
    note: "the same screens at 390 px - what stays side by side and what stacks",
    rows: [{ label: "Buying a name at phone width", kind: "phone", cells: ["M0", "M1b", "M2", "M3", "M5", "M4", "M1e"] }],
  },
  {
    title: "For the operator",
    note: "codes issued by hand, as for badges",
    rows: [{ label: "The terminal and the managed group", kind: "operator", cells: ["OP1", "OP2"] }],
  },
];

export const FRAMES = {
  N0: {
    url: HOST, label: "opened from simplex.chat, a link, or the app",
    title: "The landing page",
    text: "The badge landing with a second way in. A badge and a name are different purchases, so the landing asks which before anything else; the badge path (B2-B4) is unchanged. The app's own link opens N1 directly.",
  },
  N1: {
    url: `${HOST}/#/name`, from: "N0", label: "Get a SimpleX name", color: "blue",
    title: "The name",
    text: "One question: which name. The field fixes .simplex and folds case as it is typed. The three tiers are shown from the start, because the price depends on nothing but the length.",
  },
  N1a: {
    url: `${HOST}/#/name`, from: "N1", label: "types a name", color: "blue",
    title: "Typed",
    text: "The tier the length falls in is marked as it is typed. Nothing is sent: the name leaves the page only when Check availability is pressed, as GET /api/name/<label>.",
  },
  N1b: {
    url: `${HOST}/#/name`, from: "N1a", label: "Check availability: available", color: "blue",
    title: "Available",
    text: "The service hashed the label (keccak256), asked the resolver for [hash].simplex, and heard available. Continue opens only now. This is advice, not a hold: the code checkout makes is not bound to this name.",
  },
  N2: {
    url: `${HOST}/#/name/years`, from: "N1b", label: "Continue", color: "blue",
    title: "How long",
    text: "Two years is the floor, because the contract registers for no less than 730 days. The stepper moves a year at a time up to ten. The total is the tier's yearly price times the years, with no discount, so the arithmetic is visible.",
  },
  N3: {
    url: `${HOST}/#/name/checkout`, from: "N2", label: "Continue", color: "blue",
    title: "Check your order, and pay",
    text: "The badge checkout's shape with the name's rows. 'Your code covers names of 7+ letters' is what is bought, and the line under Pay says it again. POST /api/invoice carries kind name, the price id, the years and the code's hash, never the name.",
  },
  N5: {
    url: ORDER, from: "N3", label: "Pay with Bitcoin", color: "blue",
    title: "Paying in crypto",
    text: "Shared with badges, unchanged: the address, the amount, the QR and the held rate come from BTCPay, and the page waits on ?order= as it does for a badge.",
  },
  N6: {
    url: ORDER, from: "N5", label: "the full amount arrives", color: "blue",
    title: "Payment received",
    text: "Shared: the full amount is in and the network is confirming it. Settlement marks the code row paid, as for a badge.",
  },
  N4: {
    url: ORDER, from: "N6", label: "it confirms", color: "blue",
    title: "The name code",
    text: "SN7-2Y-... says what it covers: the shortest name and the years. Open in SimpleX hands the code and the name to the app in a link (format proposed, not yet handled by the app). Two warnings, because both are true: the name is not held until it is registered, and this browser keeps the only copy.",
  },
  N1c: {
    url: `${HOST}/#/name`, from: "N1", label: "5 letters or fewer", color: "orange",
    title: "Too short",
    text: "Judged on the page before any request: a name of 5 letters or fewer can be neither checked nor bought.",
  },
  N1d: {
    url: `${HOST}/#/name`, from: "N1", label: "a character outside a-z, 0-9, -", color: "orange",
    title: "Not a name",
    text: "Judged on the page: a-z, 0-9 and single hyphens inside the name, the rule the contract and the resolver share. Upper case is folded, not refused.",
  },
  N1e: {
    url: `${HOST}/#/name`, from: "N1a", label: "registered", color: "orange",
    title: "Taken",
    text: "The resolver answered registered. Continue stays shut and the field stays editable for another try. No expiry date is shown: a name in its grace period is still taken.",
  },
  N1f: {
    url: `${HOST}/#/name`, from: "N1a", label: "reserved", color: "orange",
    title: "Reserved",
    text: "The resolver answered reserved (internal, trademark or community). Reserved names are not sold here.",
  },
  N1g: {
    url: `${HOST}/#/name`, from: "N1a", label: "503: the resolver is down", color: "orange",
    title: "Not checked",
    text: "The resolver or its [names] section did not answer. The buyer can try again; nothing moves forward on a guess.",
  },
  N1h: {
    url: `${HOST}/#/name`, from: "N1a", label: "429", color: "orange",
    title: "Too many checks",
    text: "The read rate limit answered 429. Check stays off for Retry-After, as checkout's rate-limited screen does.",
  },
  N2a: {
    url: `${HOST}/#/name/years`, from: "N2", label: "+ up to ten", color: "orange",
    title: "Ten years",
    text: "The ceiling: plus is off at ten. Minus is off at two, as on N2.",
  },
  N2b: {
    url: `${HOST}/#/name/years`, from: "N2", label: "a 6-letter name, 3 years", color: "orange",
    title: "A 6-letter name",
    text: "Six letters cost four times the base: $200 a year, $600 for three years. Seven cost twice, $100 a year.",
  },
  A1: {
    from: "N4", label: "Open in SimpleX", color: "blue", dashed: true,
    title: "Registering in the app",
    text: "Not built here (canvas 5g, #7530): the link opens Register a name with the code and the name filled in. Commit and reveal happen there, for the app's own wallet key.",
  },
  A1a: {
    from: "A1", label: "taken in the meantime", color: "orange", dashed: true,
    title: "The name went",
    text: "Not built here: someone registered the name after the check. The code is not spent, and the app asks for another name it covers.",
  },
  N3a: {
    url: `${HOST}/#/name/checkout`, from: "N3", label: "503 provider_unavailable", color: "orange",
    title: "A method is unavailable",
    text: "Shared B4b: a provider section is missing or the provider is down. The method is shown disabled and Pay relabels to the one now chosen.",
  },
  N3b: {
    url: `${HOST}/#/name/checkout`, from: "N3", label: "catalog_changed", color: "orange",
    title: "The price changed",
    text: "Shared B4c, its copy made general ('the price changed' rather than 'the badge you chose'): the name's price id was disabled while the buyer decided. Start again returns to N0.",
  },
  N3c: {
    url: `${HOST}/#/name/checkout`, from: "N3", label: "429", color: "orange",
    title: "Too many attempts",
    text: "Shared B4d: checkout answered 429, and Pay is off for exactly Retry-After.",
  },
  N3d: {
    url: `${HOST}/#/name/checkout`, from: "N3", label: "network, 5xx, bad_request", color: "orange",
    title: "That did not go through",
    text: "The shared failure screen without the badge's invest block. Try again sends the same selection again.",
  },
  N3e: {
    url: `${HOST}/#/name/checkout`, from: "N3", label: "a card payment awaits confirmation", color: "orange",
    title: "An order is already waiting",
    text: "The shared rule: a card payment waiting to be confirmed blocks a second order, which would be a second charge. An unpaid crypto order only adds the link line.",
  },
  N5a: {
    url: ORDER, from: "N5", label: "less than the amount", color: "orange",
    title: "Part of the amount",
    text: "Shared: BTCPay saw less than the amount, and the page asks for the rest at the same address.",
  },
  N5b: {
    url: ORDER, from: "N5", label: "Cancel this invoice", color: "orange",
    title: "Cancelled",
    text: "Shared: the cancel was confirmed with nothing paid, and the provider's invoice was invalidated first.",
  },
  N7a: {
    url: ORDER, from: "N5", label: "the window closes, nothing sent", color: "orange",
    title: "Expired, nothing received",
    text: "Shared: the window closed and nothing was charged. Buy a new code starts again at N0.",
  },
  N7b: {
    url: ORDER, from: "N5a", label: "the window closes", color: "orange",
    title: "Expired, part paid",
    text: "Shared: money arrived, but not all of it before the window closed. The buyer quotes the reference.",
  },
  N8: {
    url: ORDER, from: "N3", label: "Pay with Card", color: "blue",
    title: "Paying by card",
    text: "The card lane: the name's rows over Stripe's Payment Element, drawn here as a stand-in. Pay confirms in the frame.",
  },
  N8a: {
    url: ORDER, from: "N8", label: "Stripe.js does not load", color: "orange",
    title: "The card form did not load",
    text: "Shared: Stripe.js did not arrive. Nothing was charged and the order is still open.",
  },
  N8b: {
    url: ORDER, from: "N8", label: "the card is accepted", color: "blue",
    title: "Card submitted",
    text: "Shared: a confirm that succeeded is not settlement, so the page waits for the service to say paid, then goes to N4.",
  },
  N8c: {
    url: ORDER, from: "N8b", label: "fifteen minutes, still open", color: "orange",
    title: "Taking longer than expected",
    text: "Shared: no new invoice is offered, since a charge may be in flight. The buyer keeps Check again and the reference.",
  },
  N4a: {
    url: ORDER, from: "N6", label: "settled; this browser refuses the write", color: "orange",
    title: "The code could not be saved",
    text: "Storage is full or refused. The code is shown once, and copying it is the only way to keep it.",
  },
  N4b: {
    url: ORDER, label: "a paid order opened in another browser",
    title: "Not on this device",
    text: "The code was made in the buying browser and the service holds only its hash, so support can confirm the payment by its reference but cannot show the code.",
  },
  N9: {
    url: `${HOST}/?order=k2Vn8...`, label: "?order= names no invoice",
    title: "The link does not work",
    text: "Shared: an unknown order, a mistyped link, or one retention removed.",
  },
  N10: {
    url: `${HOST}/#/codes`, label: "the menu: Your codes",
    title: "Your codes",
    text: "The shared list with name rows: the chosen name as the title (kept only in this browser), what the code covers, and the code with Copy once paid. Badge rows are unchanged.",
  },
  D0: { screen: "N0", theme: "dark", url: HOST, label: "dark theme", title: "N0, dark", text: "Every new rule is built on the existing tokens, so the dark palette needs nothing of its own." },
  D1b: { screen: "N1b", theme: "dark", url: `${HOST}/#/name`, label: "dark theme", title: "N1b, dark", text: "The field, its answer and the tiers on the dark ground." },
  D3: { screen: "N3", theme: "dark", url: `${HOST}/#/name/checkout`, label: "dark theme", title: "N3, dark", text: "The checkout, unchanged but for its rows." },
  D4: { screen: "N4", theme: "dark", url: ORDER, label: "dark theme", title: "N4, dark", text: "The QR keeps its white ground in the dark theme, so it still scans." },
  M0: { screen: "N0", url: HOST, label: "a phone", title: "N0 at 390 px", text: "The two ways in stack under the hero." },
  M1b: { screen: "N1b", url: `${HOST}/#/name`, from: "M0", label: "a name: available", color: "blue", title: "N1b at 390 px", text: "Name and .simplex on one line; the tiers stay side by side." },
  M2: { screen: "N2", url: `${HOST}/#/name/years`, from: "M1b", label: "Continue", color: "blue", title: "N2 at 390 px", text: "The stepper keeps its size; only the type steps down." },
  M3: { screen: "N3", url: `${HOST}/#/name/checkout`, from: "M2", label: "Continue", color: "blue", title: "N3 at 390 px", text: "The three methods stay side by side, as for a badge." },
  M5: { screen: "N5", url: ORDER, from: "M3", label: "Pay", color: "blue", title: "N5 at 390 px", text: "QR first, then the amount and the address." },
  M4: { screen: "N4", url: ORDER, from: "M5", label: "it confirms", color: "blue", title: "N4 at 390 px", text: "Code, the two buttons, the QR, then the warnings." },
  M1e: { screen: "N1e", url: `${HOST}/#/name`, from: "M1b", label: "another name: registered", color: "orange", title: "N1e at 390 px", text: "A taken name at phone width." },
  OP1: {
    label: "the operator's terminal, --run-cli",
    title: "Issuing by hand",
    text: "//issue name <length> [years] beside the badge forms, printing the code once. //revoke takes either kind.",
  },
  OP2: {
    label: "the managed group",
    title: "Issuing in the group",
    text: "/issue name and /bulk name for moderators and above, single use. Every member reads what is posted there, as for badge codes.",
  },
};

export const NOTES = [
  "Design document, not screenshots of a build: every web screen is rendered from mockups/screens.js on the webapp's own compiled modules and styles.css, so the shared screens are the real ones and the name screens are prototypes for nameScreens.ts.",
  "A name code is an entitlement - names of N or more letters for Y years. It is not bound to the name that was checked, because registering needs the owner's wallet key, which only the app has.",
  "The name leaves the page only on Check availability. The service hashes it for the resolver and neither logs nor stores it; checkout carries the tier, the years and the code's hash, never the name.",
  "Prices: $50 a year for 8 or more letters, twice that for 7, four times for 6; 2 to 10 years, paid once, nothing renews.",
  "Regenerate after npm run build in apps/simplex-badge-service/web with: node plans/names-codes/mockups/board.mjs",
];
