// The names board: what each frame shows, where it sits, and the arrow that reaches it.
// A frame's key is its tag on the board; `screen` names the mockup in screens.js when they differ.

export const TITLE = "SimpleX names - the store at simplex.domains, every screen";
export const SUBTITLE =
  "one tree per surface, left to right - blue is the normal path, orange a variant or a failure, grey a platform difference, " +
  "and dashed is everything that crosses between the site and the app";
export const CORNER = ["plans/names-codes/names-flow.svg", "generated by mockups/board.mjs"];

const HOST = "simplex.domains";
const ORDER = `${HOST}/?order=q7ZpL2dN9xWc4KfR8tYb1A`;

export const SECTIONS = [
  {
    title: "simplex.domains",
    note: "the names store, separate from the badges store: search a name, pay, and the service registers it for you",
    rows: [
      { label: "Registering a name, start to finish", kind: "desktop", cells: ["N1", "N1a", "N2", "N3", "N4", "N5", "N6", "N6a", "N6b", "N7"] },
      { label: "What a search can find", kind: "desktop", cells: [null, "N1b", "N1c", "N2a", "N2b", "N2c", "N2d", "N2e"] },
    ],
  },
  {
    title: "When registering does not go through",
    note: "the payment is never lost: it registers another name, becomes a code, or is retried at no charge",
    rows: [{ label: "After the payment", kind: "desktop", cells: [null, null, null, null, null, null, "N9", null, "N8", "N8a"] }],
  },
  {
    title: "Where it meets the app",
    note: "the service holds the name until the app claims it; drawn after canvas 10, built by #7530 and not here",
    rows: [{ label: "Claiming moves the name to the app's wallet", kind: "app", cells: [null, null, null, null, null, null, null, null, null, "A1", "A2"] }],
  },
  {
    title: "A code for any name",
    note: "the secondary link: a code for a length, to register a name later in the app",
    rows: [{ label: "Buying a code instead of a name", kind: "desktop", cells: [null, "C1", "C2", "C3"] }],
  },
  {
    title: "Refused at checkout",
    note: "the badge checkout's refusals, with the name's summary",
    rows: [{ label: "POST /api/invoice says no", kind: "desktop", cells: [null, null, null, "N3a", "N3b", "N3c", "N3d", "N3e"] }],
  },
  {
    title: "The other ways a payment ends",
    note: "shared with the badges store: nothing about these screens depends on what is bought",
    rows: [
      { label: "Paying in Bitcoin or Monero", kind: "desktop", cells: [null, null, null, null, "N4a", "N4b", "N4c", "N4d"] },
      { label: "Paying by card", kind: "desktop", cells: [null, null, null, null, "N10", "N10a", "N10b", "N10c"] },
      { label: "A claim code this browser cannot show, and a link to nothing", kind: "desktop", cells: [null, null, null, null, null, null, null, "N7a", "N7b", "N11"] },
    ],
  },
  {
    title: "Your names, the badges store, and the dark theme",
    note: "each store keeps its own history, on its own host; the badges store only gains a link here",
    rows: [{ label: "History, the other store, then three screens dark", kind: "desktop", cells: ["N12", null, "B0", null, "D2", "D6a", "D7"] }],
  },
  {
    title: "simplex.domains on a phone",
    note: "the same screens at 390 px",
    rows: [{ label: "Registering a name at phone width", kind: "phone", cells: ["M2", "M3", "M6a", "M7", "M2a"] }],
  },
  {
    title: "For the operator",
    note: "codes for a length, issued by hand, as for badges",
    rows: [{ label: "The terminal and the managed group", kind: "operator", cells: ["OP1", "OP2"] }],
  },
];

export const FRAMES = {
  N1: {
    url: HOST, label: "simplex.domains, or a link from the app",
    title: "Search",
    text: "The store's first screen. One field, with .simplex fixed after it; the length and characters are judged as typed. The secondary links sit where the badge pages keep their invest block, so the button stands at the same height.",
  },
  N1a: {
    url: HOST, from: "N1", label: "types a name", color: "blue",
    title: "Typed",
    text: "Nothing is sent while typing. Search asks GET /api/name/<label>, which hashes the name for the resolver.",
  },
  N2: {
    url: HOST, from: "N1a", label: "Search: available", color: "blue",
    title: "Available, with its price",
    text: "The service answers with the price of this name for 2 years, from its own price rule, which may differ by name. There is no price list and no term to choose: registration is 2 years, no more, no less.",
  },
  N3: {
    url: `${HOST}/#/checkout`, from: "N2", label: "Register dynamis.simplex", color: "blue",
    title: "Check your order, and pay",
    text: "The badge checkout with the name's rows. POST /api/invoice carries kind name and the label; the service prices it again and refuses a changed price. The line under Pay says when the name is registered.",
  },
  N4: {
    url: ORDER, from: "N3", label: "Pay with Bitcoin", color: "blue",
    title: "Paying in crypto",
    text: "Shared with badges, unchanged: the address, the amount, the QR and the held rate come from BTCPay.",
  },
  N5: {
    url: ORDER, from: "N4", label: "the full amount arrives", color: "blue",
    title: "Payment received",
    text: "Shared: the network is confirming. Settlement hands the order to the registration worker.",
  },
  N6: {
    url: ORDER, from: "N5", label: "it confirms: registration starts", color: "blue",
    title: "Committing",
    text: "The app's steps (canvas 9), run by the service: it commits the registration, owner its own registrar address, and links the transaction.",
  },
  N6a: {
    url: ORDER, from: "N6", label: "the commit is mined", color: "blue",
    title: "Waiting a minute",
    text: "The contract makes a commitment wait before it can be used. The steps live in the service, so a reload or another device shows where it is.",
  },
  N6b: {
    url: ORDER, from: "N6a", label: "60 seconds later", color: "blue",
    title: "Registering",
    text: "The register transaction, dry-run first. It counts as registered at its receipt plus 3 blocks.",
  },
  N7: {
    url: ORDER, from: "N6b", label: "registered", color: "blue",
    title: "Yours, with a claim code",
    text: "The service holds the name for the buyer. The claim code, made in this browser, moves it to the app's wallet; Open in SimpleX carries it there. It points nowhere until claimed, and the 2 years have started.",
  },
  N1b: {
    url: HOST, from: "N1", label: "5 letters or fewer", color: "orange",
    title: "Too short",
    text: "Judged on the page before any request.",
  },
  N1c: {
    url: HOST, from: "N1", label: "a character outside a-z, 0-9, -", color: "orange",
    title: "Not a name",
    text: "Judged on the page: the rule the contract and the resolver share. Upper case is folded, not refused.",
  },
  N2a: {
    url: HOST, from: "N1a", label: "taken, and linked", color: "orange",
    title: "Taken: what uses it",
    text: "The name's record lists an address and a channel. The service opens each link with its chat core for the display name and picture, and the page offers Open in SimpleX for each, as the app's search does (canvas 3b). Pictures are drawn as stand-ins here.",
  },
  N2b: {
    url: HOST, from: "N1a", label: "taken, linked to nothing", color: "orange",
    title: "Taken, pointing nowhere",
    text: "Registered without links, such as a name held for a buyer who has not claimed it yet.",
  },
  N2c: {
    url: HOST, from: "N1a", label: "reserved", color: "orange",
    title: "Reserved",
    text: "Internal, trademark and community reservations read alike, with a way to reach the SimpleX team, as the app does.",
  },
  N2d: {
    url: HOST, from: "N1a", label: "503: the resolver is down", color: "orange",
    title: "Not checked",
    text: "The resolver did not answer. The buyer can search again; nothing goes forward on a guess.",
  },
  N2e: {
    url: HOST, from: "N1a", label: "429", color: "orange",
    title: "Too many searches",
    text: "The read rate limit answered. Search stays off for Retry-After.",
  },
  N9: {
    url: ORDER, from: "N6", label: "the commit fails", color: "orange",
    title: "Paid, not registered",
    text: "Something on the chain failed and the name is still free. Try again charges nothing (canvas 10b); the service also retries by itself.",
  },
  N8: {
    url: ORDER, from: "N6b", label: "someone registered it first", color: "orange",
    title: "Someone was faster",
    text: "Taken between the search and the register call; the dry run caught it, so nothing was spent on it. The payment is kept for another name, or as a code for this length (canvas 10a).",
  },
  N8a: {
    url: HOST, from: "N8", label: "Choose another name", color: "orange",
    title: "Another name, same payment",
    text: "Search again with the order's value: any available name priced at or under what was paid registers with it.",
  },
  A1: {
    from: "N7", label: "Open in SimpleX", color: "blue", dashed: true,
    title: "Claiming in the app",
    text: "Not built here (#7530): the app sends claimName with the code, its wallet address and where the name points. The service sets the records, then transfers the name.",
  },
  A2: {
    from: "A1", label: "Claim", color: "blue", dashed: true,
    title: "The name is yours",
    text: "As canvas 10: it points at the address or channel from now on.",
  },
  C1: {
    url: `${HOST}/#/code`, from: "N1", label: "Buy a code for any name", color: "blue",
    title: "A code for a length",
    text: "The secondary link. A code covers any name of this length or longer for 2 years, chosen later in the app; prices are shown only here, one per length.",
  },
  C2: {
    url: `${HOST}/#/code/checkout`, from: "C1", label: "Continue", color: "blue",
    title: "Check the code order",
    text: "The same checkout. POST /api/invoice carries kind nameCode, the length and the code's hash.",
  },
  C3: {
    url: ORDER, from: "C2", label: "paid", color: "blue",
    title: "The code",
    text: "SN7-2Y-... says what it covers. The app registers a name with it (#7530), with the same steps.",
  },
  N3a: {
    url: `${HOST}/#/checkout`, from: "N3", label: "503 provider_unavailable", color: "orange",
    title: "A method is unavailable",
    text: "Shared: the method is shown disabled and Pay relabels to the one now chosen.",
  },
  N3b: {
    url: `${HOST}/#/checkout`, from: "N3", label: "catalog_changed", color: "orange",
    title: "The price changed",
    text: "The name's price changed while the buyer decided. Nothing was charged; Search again shows the new price.",
  },
  N3c: {
    url: `${HOST}/#/checkout`, from: "N3", label: "429", color: "orange",
    title: "Too many attempts",
    text: "Shared: Pay is off for exactly Retry-After.",
  },
  N3d: {
    url: `${HOST}/#/checkout`, from: "N3", label: "network, 5xx, bad_request", color: "orange",
    title: "That did not go through",
    text: "The shared failure screen, without an invest block. Try again sends the same order again.",
  },
  N3e: {
    url: `${HOST}/#/checkout`, from: "N3", label: "a card payment awaits confirmation", color: "orange",
    title: "An order is already waiting",
    text: "The shared rule: a second order would be a second charge.",
  },
  N4a: {
    url: ORDER, from: "N4", label: "less than the amount", color: "orange",
    title: "Part of the amount",
    text: "Shared: the page asks for the rest at the same address.",
  },
  N4b: {
    url: ORDER, from: "N4", label: "Cancel this invoice", color: "orange",
    title: "Cancelled",
    text: "Shared: nothing was paid and the provider's invoice was invalidated.",
  },
  N4c: {
    url: ORDER, from: "N4", label: "the window closes, nothing sent", color: "orange",
    title: "Expired, nothing received",
    text: "Shared: nothing was charged.",
  },
  N4d: {
    url: ORDER, from: "N4a", label: "the window closes", color: "orange",
    title: "Expired, part paid",
    text: "Shared: the buyer quotes the reference.",
  },
  N10: {
    url: ORDER, from: "N3", label: "Pay with Card", color: "blue",
    title: "Paying by card",
    text: "The card lane with the name's rows over Stripe's Payment Element, drawn as a stand-in.",
  },
  N10a: {
    url: ORDER, from: "N10", label: "Stripe.js does not load", color: "orange",
    title: "The card form did not load",
    text: "Shared: nothing was charged and the order is still open.",
  },
  N10b: {
    url: ORDER, from: "N10", label: "the card is accepted", color: "blue",
    title: "Card submitted",
    text: "Shared: once the service says paid, registration starts at N6.",
  },
  N10c: {
    url: ORDER, from: "N10b", label: "fifteen minutes, still open", color: "orange",
    title: "Taking longer than expected",
    text: "Shared: no new order is offered while a charge may be in flight.",
  },
  N7a: {
    url: ORDER, from: "N6b", label: "registered; this browser refuses the write", color: "orange",
    title: "The claim code could not be saved",
    text: "Storage is full or refused, so the code is shown once.",
  },
  N7b: {
    url: ORDER, label: "a registered order opened elsewhere",
    title: "Not on this device",
    text: "The name is held, but its claim code exists only in the buying browser; support confirms the order by reference.",
  },
  N11: {
    url: `${HOST}/?order=k2Vn8...`, label: "?order= names no invoice",
    title: "The link does not work",
    text: "Shared: an unknown or mistyped order.",
  },
  N12: {
    url: `${HOST}/#/names`, label: "the menu: Your names",
    title: "Your names",
    text: "Names registered, registering, and codes, from this browser's store. simplex.domains and badges.simplex.chat are different hosts, so each store keeps its own.",
  },
  B0: {
    url: "badges.simplex.chat", label: "badges.simplex.chat",
    title: "The badges store",
    text: "Unchanged but for one secondary link to simplex.domains; the names store links back from its search and its menu.",
  },
  D2: { screen: "N2", theme: "dark", url: HOST, label: "dark theme", title: "N2, dark", text: "Every new rule uses the existing tokens." },
  D6a: { screen: "N6a", theme: "dark", url: ORDER, label: "dark theme", title: "N6a, dark", text: "The steps on the dark ground." },
  D7: { screen: "N7", theme: "dark", url: ORDER, label: "dark theme", title: "N7, dark", text: "The QR keeps its white ground, so it still scans." },
  M2: { screen: "N2", url: HOST, label: "a phone", title: "N2 at 390 px", text: "Field, answer and price in one column." },
  M3: { screen: "N3", url: `${HOST}/#/checkout`, from: "M2", label: "Register", color: "blue", title: "N3 at 390 px", text: "The methods stay side by side." },
  M6a: { screen: "N6a", url: ORDER, from: "M3", label: "paid", color: "blue", title: "N6a at 390 px", text: "The steps at phone width." },
  M7: { screen: "N7", url: ORDER, from: "M6a", label: "registered", color: "blue", title: "N7 at 390 px", text: "Code, buttons, QR, then the warnings." },
  M2a: { screen: "N2a", url: HOST, from: "M2", label: "another name: taken", color: "orange", title: "N2a at 390 px", text: "Links hide; pictures, names and Open stay." },
  OP1: {
    label: "the operator's terminal, --run-cli",
    title: "Issuing by hand",
    text: "//issue name <length> prints a code for a length, once. //revoke takes either kind.",
  },
  OP2: {
    label: "the managed group",
    title: "Issuing in the group",
    text: "/issue name and /bulk name for moderators and above. Every member reads what is posted there.",
  },
};

export const NOTES = [
  "Design document, not screenshots of a build: every web screen is rendered from mockups/screens.js on the webapp's own compiled modules and styles.css, so the shared screens are the real ones and the name screens are prototypes for nameScreens.ts.",
  "Two stores to the user: names at simplex.domains, badges at badges.simplex.chat, each linking the other as a secondary option; one service (StoreService) and one webapp codebase behind both.",
  "Registration is 2 years, fixed. The price is the service's answer for the searched name; the price rule is internal and may change, or differ by name.",
  "The service registers a paid name to its own registrar address and holds it; the claim code, made in the buyer's browser and stored by the service only as a hash, moves it to the app's wallet.",
  "Regenerate after npm run build in apps/simplex-badge-service/web with: PLAYWRIGHT=<playwright index.mjs> node plans/names-codes/mockups/board.mjs",
];
