// The names board: what each frame shows, where it sits, and the arrow that reaches it.
// A frame's key is its tag on the board; `screen` names the mockup in screens.js when they differ.

export const TITLE = "SimpleX names - the store at simplex.domains, every screen";
export const SUBTITLE =
  "one tree per surface, left to right - blue is the normal path, orange a variant or a failure, " +
  "the dashed arrow hands off from the site to the app, and app screens are outlined in grey dashes";
export const CORNER = ["plans/names-codes/names-flow.svg", "generated by mockups/board.mjs"];

const HOST = "simplex.domains";
const ORDER = `${HOST}/?order=q7ZpL2dN9xWc4KfR8tYb1A`;

export const SECTIONS = [
  {
    title: "simplex.domains",
    note: "the names store: search a name, pay, and the name is registered to a wallet made in your browser",
    rows: [
      { label: "Registering a name, start to finish", kind: "desktop", cells: ["N1", "N1a", "N2", "N3", "N4", "N5", "N6", "N6a", "N6b", "N7"] },
      { label: "What a search can find", kind: "desktop", cells: [null, "N1b", "N1c", "N2a", "N2b", "N2c", "N2f", "N2d", "N2e"] },
    ],
  },
  {
    title: "Paying with a code",
    note: "the service's table says what a code covers, and a covered name costs $0",
    rows: [
      { label: "Check your code, then register for $0", kind: "desktop", cells: [null, null, "K1", "K2", "K3", "K8"] },
      { label: "A code at checkout, and codes that do not work", kind: "desktop", cells: [null, null, "K5", "K6", "K4", "K7"] },
    ],
  },
  {
    title: "When registering does not go through",
    note: "the payment is never lost: it registers another name, becomes a code, or is retried at no charge",
    rows: [{ label: "After the payment", kind: "desktop", cells: [null, null, null, null, null, "N9", null, "N8", "N8a", "N8b"] }],
  },
  {
    title: "Opened from the app",
    note: "the app's link carries the name and its own owner address: no phrase, no \"I have a code\"",
    rows: [{ label: "The app sends the buyer here to pay", kind: "desktop", cells: ["L1", "L2", "L3"] }],
  },
  {
    title: "Where it meets the app",
    note: "importing the phrase makes the name an account of the app's wallet; drawn as the app might, to be added to #7475/#7530, not built here",
    rows: [{ label: "Importing the recovery phrase", kind: "app", cells: [null, null, null, null, null, null, null, null, null, "A1", "A2"] }],
  },
  {
    title: "Refused at checkout",
    note: "the badge checkout's refusals, with the name's summary",
    rows: [{ label: "POST /api/invoice says no", kind: "desktop", cells: [null, null, null, "N3a", "N3b", "N3c", "N3d", "N3e"] }],
  },
  {
    title: "The other ways a payment ends",
    note: "the payment endings are the badges store's; the last row is the names store's own phrase pages, beside the shared unknown link",
    rows: [
      { label: "Paying in Bitcoin or Monero", kind: "desktop", cells: [null, null, null, null, "N4a", "N4b", "N4c", "N4d"] },
      { label: "Paying by card", kind: "desktop", cells: [null, null, null, null, "N10", "N10a", "N10b", "N10c"] },
      { label: "A phrase this browser cannot show, and a link to nothing", kind: "desktop", cells: [null, null, null, null, null, null, "N3f", "N7a", "N7b", "N11"] },
    ],
  },
  {
    title: "Your names, the badges store, and the dark theme",
    note: "each store keeps its own history, on its own host; the badges store only gains a link here",
    rows: [{ label: "History, the other store, then three screens dark", kind: "desktop", cells: ["N13", "N12", "N12a", "B0", null, "D2", "D6a", "D7"] }],
  },
  {
    title: "simplex.domains on a phone",
    note: "the same screens at 390 px",
    rows: [{ label: "Registering a name at phone width", kind: "phone", cells: ["M2", "M3", "M6a", "M7", "M2a"] }],
  },
  {
    title: "For the operator",
    note: "codes issued by hand, as for badges; they are not sold on the web",
    rows: [{ label: "The terminal and the managed group", kind: "operator", cells: ["OP1", "OP2"] }],
  },
];

export const FRAMES = {
  N1: {
    url: HOST, label: "simplex.domains",
    title: "Search",
    text: "The first screen. The field ends in .simplex and a magnifying glass: the glass, Enter and the Search button all search. The rules line stays hidden until a mistake. The invest block keeps the badge pages' place under the button, with Check your code.",
  },
  N1a: {
    url: HOST, from: "N1", label: "types a name", color: "blue",
    title: "Typed",
    text: "Nothing is sent while typing. Search asks GET /api/name/:label, which hashes the name for the resolver.",
  },
  N2: {
    url: HOST, from: "N1a", label: "Search: available", color: "blue",
    title: "Available, with its price",
    text: "The service's price for this name for 2 years; prices are internal and may differ by name. No price list, no term to choose.",
  },
  N3: {
    url: `${HOST}/#/checkout`, from: "N2", label: "Register dynamis.simplex", color: "blue",
    title: "Check your order, and pay",
    text: "Here the browser makes the name's wallet: 128-bit entropy, a 12-word phrase, the address at m/44'/60'/0'/0/0, stored before the order is created. Only the address goes with the order. I have a code sits under Pay.",
  },
  N4: {
    url: ORDER, from: "N3", label: "Pay with Bitcoin", color: "blue",
    title: "Paying in crypto",
    text: "Shared with badges.",
  },
  N5: {
    url: ORDER, from: "N4", label: "the full amount arrives", color: "blue",
    title: "Payment received",
    text: "Shared: settlement hands the order to the registration worker.",
  },
  N6: {
    url: ORDER, from: "N5", label: "it confirms: registration starts", color: "blue",
    title: "Committing",
    text: "The app's steps (canvas 9), run by the service from its own funded key, with the buyer's address as owner. The name belongs to that address from the start: nothing is held for anyone.",
  },
  N6a: {
    url: ORDER, from: "N6", label: "the commit is mined", color: "blue",
    title: "Waiting a minute",
    text: "The controller's minCommitmentAge. The steps live in the service, so a reload or another device shows where it is.",
  },
  N6b: {
    url: ORDER, from: "N6a", label: "60 seconds later", color: "blue",
    title: "Registering",
    text: "The register transaction, dry-run first; registered at its receipt plus 3 blocks.",
  },
  N7: {
    url: ORDER, from: "N6b", label: "registered", color: "blue",
    title: "Yours, with its recovery phrase",
    text: "The 12 words own the name; the QR carries them to the app. The phrase never left this browser, so nobody can make another: the page says to write it down.",
  },
  N1b: {
    url: HOST, from: "N1a", label: "Search, with 5 letters", color: "orange",
    title: "Too short",
    text: "Judged when searching, not while typing: the rules line appears only now, after the mistake. Editing the name and searching again is the way on.",
  },
  N1c: {
    url: HOST, from: "N1a", label: "Search, with a character outside a-z, 0-9, -", color: "orange",
    title: "Not a name",
    text: "Judged on the page; upper case is folded as typed, not refused.",
  },
  N2a: {
    url: HOST, from: "N1a", label: "taken, and linked", color: "orange",
    title: "Taken: what uses it",
    text: "The record's address and channel, as canvas 3b. The display name and picture, read by the service's chat core (APIConnectPlan), and Open in SimpleX are this store's addition. Pictures are drawn as stand-ins.",
  },
  N2b: {
    url: HOST, from: "N1a", label: "taken, linked to nothing", color: "orange",
    title: "Taken, pointing nowhere",
    text: "Registered without links, such as a name bought here whose owner has not set records yet.",
  },
  N2c: {
    url: HOST, from: "N1a", label: "reserved", color: "orange",
    title: "Reserved",
    text: "With a way to reach the SimpleX team, as the app does.",
  },
  N2f: {
    url: HOST, from: "N1a", label: "held by another order", color: "orange",
    title: "Being registered",
    text: "Another order holds the name. A second order is refused (name_pending), so two buyers never pay for one name.",
  },
  N2d: {
    url: HOST, from: "N1a", label: "503: the resolver is down", color: "orange",
    title: "Not checked",
    text: "Nothing goes forward on a guess.",
  },
  N2e: {
    url: HOST, from: "N1a", label: "429", color: "orange",
    title: "Too many searches",
    text: "Search stays off for Retry-After.",
  },
  K1: {
    url: HOST, from: "N2", label: "Check your code", color: "blue",
    title: "Check your code",
    text: "A popup over the search: POST /api/code/check says what the code covers and that it is unused, spending nothing. This is an investor code, SN- for any name and 7 years; the service's table, not the text, decides.",
  },
  K2: {
    url: HOST, from: "K1", label: "Use this code", color: "blue",
    title: "Covered: $0",
    text: "While the code is applied, a name it covers shows $0 and the code's own term, 7 years here.",
  },
  K3: {
    url: `${HOST}/#/checkout`, from: "K2", label: "Register with code", color: "blue",
    title: "Checkout at $0",
    text: "No payment step: POST /api/name/register reserves the code, and the steps start as at N6, on ?registration=<id>; the code is spent when the name registers.",
  },
  K8: {
    url: `${HOST}/?registration=r4Hq9TzW2mXc7LpN5vBd8k`, from: "K3", label: "the steps finish, as N6-N7", color: "blue",
    title: "Yours for the code's term",
    text: "The registered screen with the code's years: 7 for this investor code. The phrase is handled as in N7.",
  },
  K5: {
    url: HOST, from: "N2", label: "a used code", color: "orange",
    title: "Already used",
    text: "Each code registers one name.",
  },
  K6: {
    url: HOST, from: "N2", label: "a mistyped code", color: "orange",
    title: "Not valid",
    text: "The check character catches a typo before any request.",
  },
  K4: {
    url: `${HOST}/#/checkout`, from: "N3", label: "I have a code", color: "blue",
    title: "A code at checkout",
    text: "I have a code opens the entry in place; a covering code turns Pay into Register with code.",
  },
  K7: {
    url: `${HOST}/#/checkout`, from: "N3", label: "a code for longer names", color: "orange",
    title: "Does not cover this name",
    text: "The code covers 8+ letters and the name has 7; the buyer can still pay.",
  },
  N9: {
    url: ORDER, from: "N6", label: "the commit fails", color: "orange",
    title: "Paid, not registered",
    text: "The name is still free. The service retried by itself and gave up; Try again (POST /api/registration/:id/retry) charges nothing (canvas 10b). Refunds are manual.",
  },
  N8: {
    url: ORDER, from: "N6b", label: "registered elsewhere first", color: "orange",
    title: "Someone was faster",
    text: "Possible only for names registered outside the store. The commit was mined, but the register dry run caught it, so register was never sent. The payment is kept (canvas 10a). A code order ends here too, its code released unspent (not drawn).",
  },
  N8a: {
    url: ORDER, from: "N8", label: "Choose another name", color: "orange",
    title: "Another name, same payment",
    text: "Search on the order's own page: any name at or under what was paid, registered to the same wallet, so the phrase owns the new name. A cheaper one refunds nothing; a dearer one cannot be registered.",
  },
  N8b: {
    url: ORDER, from: "N8", label: "Take a code", color: "orange",
    title: "A code instead",
    text: "The service issues a code for the original name's price tier (its length, 8+ for longer names), for 2 years. The browser keeps it under Your names; the service keeps only its hash.",
  },
  L1: {
    url: `${HOST}/#/?name=dynamis&owner=0x2F0b…94aE`, label: "the app's link",
    title: "Opened from the app",
    text: "The app passes the name it searched and its own account's address, shown here and at checkout so a crafted link cannot pass unnoticed. The page makes no wallet.",
  },
  L2: {
    url: `${HOST}/#/checkout`, from: "L1", label: "Register", color: "blue",
    title: "Checkout, without I have a code",
    text: "The app redeems codes itself, so this flow offers only card, Bitcoin and Monero.",
  },
  L3: {
    url: ORDER, from: "L2", label: "paid, then the steps as N6", color: "blue",
    title: "Back to SimpleX",
    text: "Registered straight to the app's account: nothing to import.",
  },
  A1: {
    from: "N7", label: "scan the phrase with the app", color: "blue", dashed: true,
    title: "Importing in the app",
    text: "Not built here: #7475's wallet imports a phrase only as the device's single master, so adding a name's 12 words beside an existing master is new app work, to be added to #7475/#7530.",
  },
  A2: {
    from: "A1", label: "Import", color: "blue",
    title: "The name is in the app",
    text: "After canvas 10's alert, without its \"points at\" line: a name bought here has no records yet.",
  },
  N3a: {
    url: `${HOST}/#/checkout`, from: "N3", label: "503 provider_unavailable", color: "orange",
    title: "A method is unavailable",
    text: "Shared: shown disabled, Pay relabels.",
  },
  N3b: {
    url: `${HOST}/#/checkout`, from: "N3", label: "catalog_changed", color: "orange",
    title: "The price changed",
    text: "Nothing was charged; Search again shows the new price.",
  },
  N3c: {
    url: `${HOST}/#/checkout`, from: "N3", label: "429", color: "orange",
    title: "Too many attempts",
    text: "Shared: Pay is off for Retry-After.",
  },
  N3d: {
    url: `${HOST}/#/checkout`, from: "N3", label: "network, 5xx, bad_request", color: "orange",
    title: "That did not go through",
    text: "A prototype of the shared failure screen without its badge invest block; stage 5 makes that block optional.",
  },
  N3e: {
    url: `${HOST}/#/checkout`, from: "N3", label: "a card payment awaits confirmation", color: "orange",
    title: "An order is already waiting",
    text: "The shared rule: a second order would be a second charge.",
  },
  N4a: { url: ORDER, from: "N4", label: "less than the amount", color: "orange", title: "Part of the amount", text: "Shared." },
  N4b: { url: ORDER, from: "N4", label: "Cancel this invoice", color: "orange", title: "Cancelled", text: "Shared; the new-invoice button reads Get a new invoice here, not Buy a new code." },
  N4c: { url: ORDER, from: "N4", label: "the window closes, nothing sent", color: "orange", title: "Expired, nothing received", text: "Shared." },
  N4d: { url: ORDER, from: "N4a", label: "the window closes", color: "orange", title: "Expired, part paid", text: "Shared: the buyer quotes the reference." },
  N10: {
    url: ORDER, from: "N3", label: "Pay with Card", color: "blue",
    title: "Paying by card",
    text: "The name's rows over Stripe's Payment Element, drawn as a stand-in.",
  },
  N10a: { url: ORDER, from: "N10", label: "Stripe.js does not load", color: "orange", title: "The card form did not load", text: "Shared, with Get a new invoice." },
  N10b: { url: ORDER, from: "N10", label: "the card is accepted", color: "blue", title: "Card submitted", text: "Shared: once paid, registration starts at N6." },
  N10c: { url: ORDER, from: "N10b", label: "fifteen minutes, still open", color: "orange", title: "Taking longer than expected", text: "Shared." },
  N7a: {
    url: ORDER, from: "N3f", label: "paid anyway, then registered", color: "orange",
    title: "The phrase could not be saved",
    text: "Storage was refused at checkout, which warned (\"This browser will not keep your recovery phrase\"); the phrase lived in memory and is shown once.",
  },
  N3f: {
    url: `${HOST}/#/checkout`, from: "N3", label: "this browser refuses storage", color: "orange",
    title: "The phrase will not be kept",
    text: "Checked before the order is created. The buyer can still pay; the phrase then lives only in this page.",
  },
  N7b: {
    url: ORDER, label: "a registered order opened elsewhere",
    title: "Not on this device",
    text: "The name is registered, but its phrase exists only in the buying browser. Nobody can make another, and the page says so.",
  },
  N11: { url: `${HOST}/?order=k2Vn8...`, label: "?order= names no invoice", title: "This link does not work", text: "Shared." },
  N12: {
    url: `${HOST}/#/names`, from: "N13", label: "Your names", color: "blue",
    title: "Your names",
    text: "Seen a little after the dynamis order completed. Names with their phrases (shown on request), registrations in progress, and codes. Each store keeps its own history, on its own host.",
  },
  N13: {
    url: HOST, label: "the menu",
    title: "The menu",
    text: "The shared menu, relabelled for names, with the badges store linked at its end.",
  },
  N12a: {
    url: `${HOST}/#/names`, from: "N12", label: "Check a code", color: "blue",
    title: "Check a code",
    text: "Asks the service what a code covers and adds it to the list, where Use applies it to a search.",
  },
  B0: {
    url: "badges.simplex.chat", from: "N13", label: "SimpleX badges", color: "blue",
    title: "The badges store",
    text: "Unchanged but for one link to simplex.domains; the names store links back from its menu.",
  },
  D2: { screen: "N2", theme: "dark", url: HOST, label: "dark theme", title: "N2, dark", text: "Every new rule uses the existing tokens." },
  D6a: { screen: "N6a", theme: "dark", url: ORDER, label: "dark theme", title: "N6a, dark", text: "The steps on the dark ground." },
  D7: { screen: "N7", theme: "dark", url: ORDER, label: "dark theme", title: "N7, dark", text: "The QR keeps its white ground, so it still scans." },
  M2: { screen: "N2", url: HOST, label: "a phone", title: "N2 at 390 px", text: "Field, glass, answer and price in one column." },
  M3: { screen: "N3", url: `${HOST}/#/checkout`, from: "M2", label: "Register", color: "blue", title: "N3 at 390 px", text: "The methods stay side by side." },
  M6a: { screen: "N6a", url: ORDER, from: "M3", label: "paid", color: "blue", title: "N6a at 390 px", text: "The steps at phone width." },
  M7: { screen: "N7", url: ORDER, from: "M6a", label: "registered", color: "blue", title: "N7 at 390 px", text: "The phrase in two columns." },
  M2a: { screen: "N2a", url: HOST, from: "M2", label: "another name: taken", color: "orange", title: "N2a at 390 px", text: "Links hide; pictures, names and Open stay." },
  OP1: {
    label: "the operator's terminal, --run-cli",
    title: "Issuing by hand",
    text: "//issue name [length] [years]: SN7- for a length, SN- for any name (investors, 7 years here), 2 years by default. //revoke takes either kind.",
  },
  OP2: {
    label: "the managed group",
    title: "Issuing in the group",
    text: "/issue name and /bulk name for moderators and above; every member reads what is posted.",
  },
};

export const NOTES = [
  "Design document, not screenshots of a build: every web screen is rendered from mockups/screens.js on the webapp's own compiled modules and styles.css, so the shared screens are the real ones and the name screens are prototypes for nameScreens.ts.",
  "Two stores to the user: names at simplex.domains, badges at badges.simplex.chat; one service (StoreService) and one webapp codebase behind both.",
  "Non-custodial: the browser makes each name's wallet (128-bit entropy, a 12-word BIP-39 phrase, account m/44'/60'/0'/0/0) with vendored @noble/secp256k1 and @noble/hashes, and sends only the address; the service pays for and sends commit and register with that owner.",
  "A paid name registers for 2 years, a code for its own term; the price is the service's answer for the searched name. Codes (SN6-, SN-, ...) come from the operator, the app (not yet in #7530) or, for a taken order, the service; never sold here; the service's table is their truth.",
  "Regenerate after npm run build in apps/simplex-badge-service/web with: PLAYWRIGHT=<playwright index.mjs> node plans/names-codes/mockups/board.mjs",
];
