{-# LANGUAGE QuasiQuotes #-}

module Simplex.Chat.Store.Postgres.Migrations.M20251007_connections_sync where

import Data.Text (Text)
import qualified Data.Text as T
import Text.RawString.QQ (r)

m20251007_connections_sync :: Text
m20251007_connections_sync =
  T.pack
    [r|
CREATE TABLE connections_sync(
  connections_sync_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  should_sync SMALLINT NOT NULL DEFAULT 0,
  last_sync_ts TIMESTAMPTZ
);

INSERT INTO connections_sync (connections_sync_id, should_sync, last_sync_ts) VALUES (1,0,NULL);
|]

down_m20251007_connections_sync :: Text
down_m20251007_connections_sync =
  T.pack
    [r|
DROP TABLE connections_sync;
|]
