sequenceDiagram
  participant Alice
  participant App A
  participant Server A
  participant Server B
  participant App B
  participant Bob
  Alice ->> App A: Alice writes the message to Bob in the app
  App A ->> Server A: The message (including ID & timestamp) is encrypted with Bob's <BA public key> and sent to all Alice's servers<br>{from: <AB public key hash>, to: <BA public key hash>, message: <encrypted with BA public key>}
  Server A ->> Server B: Alice's servers use <BA public key hash> to locate Bob's servers<br>and forward encrypted message to all Bob's servers (when they are different from Alice's servers
  Server B ->> App B: Bob's servers send the message to Bob's app
  App B ->> Bob: Bob's app uses <AB public key hash> to identify Alice<br>and decrypts the messages with Bob's <BA private key>
