{-# LANGUAGE LambdaCase #-}

module Simplex.Chat.Bot.Commands where

import qualified Data.Aeson as J
import qualified Data.ByteString.Char8 as B
import qualified Data.ByteString.Lazy.Char8 as LB
import qualified Data.Text as T
import Simplex.Chat.Controller
import Simplex.Chat.Messages
import Simplex.Chat.Messages.CIContent
import Simplex.Messaging.Encoding.String
import Simplex.Messaging.Util (safeDecodeUtf8)
import Simplex.Chat.Core (sendChatCmd)

sendChatCmd' :: ChatController -> ChatCommand -> IO ChatResponse
sendChatCmd' cc = sendChatCmd cc . serializeChatCommand

serializeChatCommand :: ChatCommand -> String
serializeChatCommand = \case
  ShowActiveUser -> ""
  CreateActiveUser _ -> ""
  ListUsers -> ""
  APISetActiveUser {} -> ""
  SetActiveUser {} -> ""
  SetAllContactReceipts _ -> ""
  APISetUserContactReceipts {} -> ""
  SetUserContactReceipts {} -> ""
  APIHideUser {} -> ""
  APIUnhideUser {} -> ""
  APIMuteUser {} -> ""
  APIUnmuteUser {} -> ""
  HideUser {} -> ""
  UnhideUser {} -> ""
  MuteUser -> ""
  UnmuteUser -> ""
  APIDeleteUser {} -> ""
  DeleteUser {} -> ""
  StartChat {} -> ""
  APIStopChat -> ""
  APIActivateChat -> ""
  APISuspendChat {} -> ""
  ResubscribeAllConnections -> ""
  SetTempFolder {} -> ""
  SetFilesFolder {} -> ""
  APISetXFTPConfig {} -> ""
  SetIncognito {} -> ""
  APIExportArchive {} -> ""
  ExportArchive -> ""
  APIImportArchive {} -> ""
  APIDeleteStorage -> ""
  APIStorageEncryption {} -> ""
  ExecChatStoreSQL {} -> ""
  ExecAgentStoreSQL {} -> ""
  APIGetChats {} -> ""
  APIGetChat cRef pagination search_ -> "/_get chat " <> chatRefStr cRef <> chatPaginationStr pagination <> searchStr search_
  APIGetChatItems {} -> ""
  APIGetChatItemInfo {} -> ""
  APISendMessage cRef live ciTtl cm -> "/_send " <> chatRefStr cRef <> liveStr live <> ttlStr ciTtl <> " json " <> jsonEncode cm
  APIUpdateChatItem {} -> ""
  APIDeleteChatItem cRef ciId mode -> unwords ["/_delete item", chatRefStr cRef, show ciId, ciDeleteModeStr mode]
  APIDeleteMemberChatItem {} -> ""
  APIChatItemReaction {} -> ""
  APIChatRead {} -> ""
  APIChatUnread {} -> ""
  APIDeleteChat {} -> ""
  APIClearChat {} -> ""
  APIAcceptContact {} -> ""
  APIRejectContact {} -> ""
  APISendCallInvitation {} -> ""
  SendCallInvitation {} -> ""
  APIRejectCall {} -> ""
  APISendCallOffer {} -> ""
  APISendCallAnswer {} -> ""
  APISendCallExtraInfo {} -> ""
  APIEndCall {} -> ""
  APIGetCallInvitations -> ""
  APICallStatus {} -> ""
  APIUpdateProfile {} -> ""
  APISetContactPrefs {} -> ""
  APISetContactAlias {} -> ""
  APISetConnectionAlias {} -> ""
  APIParseMarkdown {} -> ""
  APIGetNtfToken {} -> ""
  APIRegisterToken {} -> ""
  APIVerifyToken {} -> ""
  APIDeleteToken {} -> ""
  APIGetNtfMessage {} -> ""
  APIAddMember {} -> ""
  APIJoinGroup gId -> "/_join #" <> show gId
  APIMemberRole {} -> ""
  APIRemoveMember {} -> ""
  APILeaveGroup {} -> ""
  APIListMembers {} -> ""
  APIUpdateGroupProfile {} -> ""
  APICreateGroupLink gId r -> "/_create link #" <> show gId <> " " <> memberRoleStr r
  APIGroupLinkMemberRole {} -> ""
  APIDeleteGroupLink {} -> ""
  APIGetGroupLink {} -> ""
  APIGetUserProtoServers {} -> ""
  GetUserProtoServers {} -> ""
  APISetUserProtoServers {} -> ""
  SetUserProtoServers {} -> ""
  APITestProtoServer {} -> ""
  TestProtoServer {} -> ""
  APISetChatItemTTL {} -> ""
  SetChatItemTTL {} -> ""
  APIGetChatItemTTL {} -> ""
  GetChatItemTTL -> ""
  APISetNetworkConfig {} -> ""
  APIGetNetworkConfig -> ""
  ReconnectAllServers -> ""
  APISetChatSettings {} -> ""
  APIContactInfo {} -> ""
  APIGroupMemberInfo {} -> ""
  APISwitchContact {} -> ""
  APISwitchGroupMember {} -> ""
  APIAbortSwitchContact {} -> ""
  APIAbortSwitchGroupMember {} -> ""
  APISyncContactRatchet {} -> ""
  APISyncGroupMemberRatchet {} -> ""
  APIGetContactCode {} -> ""
  APIGetGroupMemberCode {} -> ""
  APIVerifyContact {} -> ""
  APIVerifyGroupMember {} -> ""
  APIEnableContact {} -> ""
  APIEnableGroupMember {} -> ""
  SetShowMessages {} -> ""
  SetSendReceipts {} -> ""
  ContactInfo {} -> ""
  GroupMemberInfo {} -> ""
  SwitchContact {} -> ""
  SwitchGroupMember {} -> ""
  AbortSwitchContact {} -> ""
  AbortSwitchGroupMember {} -> ""
  SyncContactRatchet {} -> ""
  SyncGroupMemberRatchet {} -> ""
  GetContactCode {} -> ""
  GetGroupMemberCode {} -> ""
  VerifyContact {} -> ""
  VerifyGroupMember {} -> ""
  EnableContact {} -> ""
  EnableGroupMember {} -> ""
  ChatHelp {} -> ""
  Welcome -> ""
  APIAddContact {} -> ""
  AddContact -> ""
  APIConnect {} -> ""
  Connect {} -> ""
  ConnectSimplex {} -> ""
  DeleteContact {} -> ""
  ClearContact {} -> ""
  APIListContacts {} -> ""
  ListContacts -> ""
  APICreateMyAddress {} -> ""
  CreateMyAddress -> "/address"
  APIDeleteMyAddress {} -> ""
  DeleteMyAddress -> ""
  APIShowMyAddress {} -> ""
  ShowMyAddress -> "/show_address"
  APISetProfileAddress {} -> ""
  SetProfileAddress {} -> ""
  APIAddressAutoAccept {} -> ""
  AddressAutoAccept {} -> ""
  AcceptContact {} -> ""
  RejectContact {} -> ""
  SendMessage {} -> ""
  SendLiveMessage {} -> ""
  SendMessageQuote {} -> ""
  SendMessageBroadcast {} -> ""
  DeleteMessage {} -> ""
  DeleteMemberMessage {} -> ""
  EditMessage {} -> ""
  UpdateLiveMessage {} -> ""
  ReactToMessage {} -> ""
  APINewGroup {} -> ""
  NewGroup {} -> ""
  AddMember {} -> ""
  JoinGroup {} -> ""
  MemberRole {} -> ""
  RemoveMember {} -> ""
  LeaveGroup {} -> ""
  DeleteGroup {} -> ""
  ClearGroup {} -> ""
  ListMembers {} -> ""
  APIListGroups {} -> ""
  ListGroups {} -> ""
  UpdateGroupNames {} -> ""
  ShowGroupProfile {} -> ""
  UpdateGroupDescription {} -> ""
  CreateGroupLink {} -> ""
  GroupLinkMemberRole {} -> ""
  DeleteGroupLink {} -> ""
  ShowGroupLink {} -> ""
  SendGroupMessageQuote {} -> ""
  LastChats {} -> ""
  LastMessages {} -> ""
  LastChatItemId {} -> ""
  ShowChatItem {} -> ""
  ShowChatItemInfo {} -> ""
  ShowLiveItems {} -> ""
  SendFile {} -> ""
  SendImage {} -> ""
  ForwardFile {} -> ""
  ForwardImage {} -> ""
  SendFileDescription {} -> ""
  ReceiveFile {} -> ""
  SetFileToReceive {} -> ""
  CancelFile {} -> ""
  FileStatus {} -> ""
  ShowProfile {} -> ""
  UpdateProfile {} -> ""
  UpdateProfileImage {} -> ""
  ShowProfileImage -> ""
  SetUserFeature {} -> ""
  SetContactFeature {} -> ""
  SetGroupFeature {} -> ""
  SetUserTimedMessages {} -> ""
  SetContactTimedMessages {} -> ""
  SetGroupTimedMessages {} -> ""
  QuitChat -> ""
  ShowVersion -> ""
  DebugLocks -> ""
  GetAgentStats -> ""
  ResetAgentStats {} -> ""
  where
    jsonEncode = T.unpack . safeDecodeUtf8 . LB.toStrict . J.encode
    chatRefStr (ChatRef cType cId) = chatTypeStr cType <> show cId
    liveStr = (" live=" <>) . onOff
    ttlStr = maybe "" $ (" ttl=" <>) . show
    chatPaginationStr = \case
      CPLast n -> count n
      CPAfter after n -> " after=" <> show after <> count n
      CPBefore before n -> " before=" <> show before <> count n
      where
        count n = " count=" <> show n
    searchStr = maybe "" (" search=" <>)
    memberRoleStr = B.unpack . strEncode 
    ciDeleteModeStr = \case
      CIDMBroadcast -> "broadcast"
      CIDMInternal -> "internal"
    onOff True = "on"
    onOff False = "off"
