{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE OverloadedLists #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE NamedFieldPuns #-}

module API.Docs.Commands where

import API.TypeInfo
import Data.ByteString.Char8 (ByteString)
import Data.String
import Data.Text (Text)

chatCommandsDocs :: [CCCategory]
chatCommandsDocs = map toCategory chatCommandsDocsData
  where
    toCategory (categoryName, categoryDescr, commandsData) =
      CCCategory {categoryName, categoryDescr, commands = map toCmd commandsData}
    toCmd (consName, syntax, description, responses, errors, network) =
      CCDoc {consName, syntax, description, responses, errors, network}

data CCCategory = CCCategory
  { categoryName :: Text,
    categoryDescr :: Text,
    commands :: [CCDoc]
  }

data CCDoc = CCDoc
  { consName :: ConsName,
    syntax :: ByteString,
    description :: Text,
    responses :: [TypeDoc],
    errors :: [TypeDoc],
    network :: UsesNetwork
  }

data TypeDoc = TD
  { consName :: ConsName,
    description :: Text
  }

type TypeDocTuple = (ConsName, Text)

type UsesNetwork = Bool

instance IsString TypeDoc where fromString s = TD s ""


-- category name, category description, commands
-- inner: constructor, syntax, description, responses, errors (ChatErrorType constructors)
chatCommandsDocsData :: [(Text, Text, [(ConsName, ByteString, Text, [TypeDoc], [TypeDoc], UsesNetwork)])]
chatCommandsDocsData =
  [ ( "Address commands",
      "Bots can use these commands to automatically check and create address when initialized",
      [ ("APICreateMyAddress", "", "", [], [], False),
        ("APIDeleteMyAddress", "", "", [], [], False),
        ("APIShowMyAddress", "", "", [], [], False),
        ("APISetProfileAddress", "", "", [], [], False),
        ("APISetAddressSettings", "", "", [], [], False)
      ]
    ),
    ( "Message commands",
      "Commands to send, update, delete, moderate messages and set message reactions",
      [ ("APISendMessages", "", "", [], [], False),
        ("APIReportMessage", "", "", [], [], False),
        ("APIUpdateChatItem", "", "", [], [], False),
        ("APIDeleteChatItem", "", "", [], [], False),
        ("APIDeleteMemberChatItem", "", "", [], [], False),
        ("APIChatItemReaction", "", "", [], [], False),
        ("APIGetReactionMembers", "", "", [""], [], False)
      ]
    ),
    ( "File commands",
      "Commands to receive and to cancel files. Files are sent as part of the message, there are no separate commands to send files.",
      [ ("ReceiveFile", "", "", [], [], False),
        ("CancelFile", "", "", [], [], False)
      ]
    ),
    ( "Group commands",
      "Commands to create and manage groups. These commands have to be used to manage business chats as well - they are groups. E.g., a common scenario would be to add human agents to business chat with the customer who connected via business address.",
      [ ("APINewGroup", "", "", [], [], False),
        ("APIAddMember", "", "", [], [], False),
        ("APIJoinGroup", "", "", [], [], False),
        ("APIAcceptMember", "", "", [], [], False),
        ("APIDeleteMemberSupportChat", "", "", [], [], False),
        ("APIMembersRole", "", "", [], [], False),
        ("APIBlockMembersForAll", "", "", [], [], False),
        ("APIRemoveMembers", "", "", [], [], False),
        ("APILeaveGroup", "", "", [], [], False),
        ("APIListMembers", "", "", [], [], False),
        ("APIUpdateGroupProfile", "", "", [], [], False),
        ("APICreateGroupLink", "", "", [], [], False),
        ("APIGroupLinkMemberRole", "", "", [], [], False),
        ("APIDeleteGroupLink", "", "", [], [], False),
        ("APIGetGroupLink", "", "", [], [], False)
      ]
    ),
    ( "Connection commands",
      "These commands may be used to establish connections. Most bots do not need to use them - bot users will connect via bot address with auto-accept enabled.",
      [ ("APIAddContact", "", "", [], [], False),
        ("APIConnect", "", "", [], [], False),
        ("APIAcceptContact", "", "", [], [], False),
        ("APIRejectContact", "", "", [], [], False)
      ]
    ),
    ( "User profile commands",
      "Most bots don't need to use these commands, as bot profile can be configured manually via CLI or desktop client. These commands can be used by bots that need to manage multiple user profiles (e.g., the profiles of support agents).",
      [ ("ShowActiveUser", "/user", "Get active user profile", ["CRActiveUser"], [], False),
        ("CreateActiveUser", "/_create user <json(NewUser)>", "Create new user profile", ["CRActiveUser"], ["CEUserExists", "CEInvalidDisplayName"], False),
        ("ListUsers", "/users", "Get all user profiles", ["CRUsersList"], [], False),
        ("APISetActiveUser", "/_user <UserId>[ <quoted(UserPwd)>]", "Set active user profile", ["CRActiveUser"], ["CEChatNotStarted"], False),
        ("APIDeleteUser", "", "", [], [], True),
        ("APIUpdateProfile", "", "", [], [], False)
      ]
    ),
    ( "Chat commands",
      "Commands to get and to manage coversations.",
      [ ("APIGetChats", "", "", [], [], False),
        ("APIGetChat", "", "", [], [], False),
        ("APIGetChatItems", "", "", [], [], False),
        ("APIGetChatItemInfo", "", "", [], [], False),
        ("APIChatRead", "", "", [], [], False),
        ("APIChatItemsRead", "", "", [], [], False),
        ("APIChatUnread", "", "", [], [], False),
        ("APIDeleteChat", "", "", [], [], False),
        ("APIClearChat", "", "", [], [], False),
        ("APISetContactPrefs", "", "", [], [], False),
        ("APISetContactAlias", "", "", [], [], False),
        ("APISetGroupAlias", "", "", [], [], False),
        ("APISetConnectionAlias", "", "", [], [], False),
        ("APISetChatTTL", "", "", [], [], False),
        ("APISetChatSettings", "", "", [], [], False),
        ("APISyncContactRatchet", "", "", [], [], False),
        ("APISyncGroupMemberRatchet", "", "", [], [], False),
        ("APIListContacts", "", "", [], [], False),
        ("APIListGroups", "", "", ["CRGroupsList"], [], False)
      ]
    )
  ]

cliCommands :: [ConsName]
cliCommands =
  [ "SetActiveUser",
    "SetUserContactReceipts",
    "SetUserGroupReceipts",
    "HideUser",
    "UnhideUser",
    "MuteUser",
    "UnmuteUser",
    "DeleteUser",
    "ReportMessage",
    "UserRead",
    "SendCallInvitation",
    "SetChatTTL",
    "GetChatTTL",
    "SetShowMessages",
    "SetSendReceipts",
    "SetShowMemberMessages",
    "ContactInfo",
    "ShowGroupInfo",
    "GroupMemberInfo",
    "ContactQueueInfo",
    "GroupMemberQueueInfo",
    "SwitchContact",
    "SwitchGroupMember",
    "AbortSwitchContact",
    "AbortSwitchGroupMember",
    "SyncContactRatchet",
    "SyncGroupMemberRatchet",
    "GetContactCode",
    "GetGroupMemberCode",
    "VerifyContact",
    "VerifyGroupMember",
    "EnableContact",
    "EnableGroupMember",
    "ChatHelp",
    "Welcome",
    "AddContact",
    "Connect",
    "ConnectSimplex",
    "DeleteContact",
    "ClearContact",
    "ListContacts",
    "CreateMyAddress",
    "DeleteMyAddress",
    "ShowMyAddress",
    "SetProfileAddress",
    "SetAddressSettings",
    "AcceptContact",
    "RejectContact",
    "ForwardMessage",
    "ForwardGroupMessage",
    "ForwardLocalMessage",
    "SendMessage",
    "SendMemberContactMessage",
    "SendLiveMessage",
    "SendMessageQuote",
    "SendMessageBroadcast",
    "DeleteMessage",
    "DeleteMemberMessage",
    "EditMessage",
    "UpdateLiveMessage",
    "ReactToMessage",
    "NewGroup",
    "AddMember",
    "JoinGroup",
    "AcceptMember",
    "MemberRole",
    "BlockForAll",
    "RemoveMembers",
    "LeaveGroup",
    "DeleteGroup",
    "ClearGroup",
    "ListMembers",
    "ListMemberSupportChats",
    "ListGroups",
    "UpdateGroupNames",
    "ShowGroupProfile",
    "UpdateGroupDescription",
    "ShowGroupDescription",
    "CreateGroupLink",
    "GroupLinkMemberRole",
    "DeleteGroupLink",
    "ShowGroupLink",
    "SendGroupMessageQuote",
    "ClearNoteFolder",
    "LastChats",
    "LastMessages",
    "LastChatItemId",
    "ShowChatItem",
    "ShowChatItemInfo",
    "ShowLiveItems",
    "SendFile",
    "SendImage",
    "ForwardFile",
    "ForwardImage",
    "SendFileDescription",
    "FileStatus",
    "ShowProfile",
    "UpdateProfile",
    "UpdateProfileImage",
    "ShowProfileImage",
    "SetUserFeature",
    "SetContactFeature",
    "SetGroupFeature",
    "SetGroupFeatureRole",
    "SetGroupMemberAdmissionReview",
    "SetUserTimedMessages",
    "SetContactTimedMessages",
    "SetGroupTimedMessages",
    "SetLocalDeviceName",
    "QuitChat",
    "ShowVersion"
  ]

undocdCommands :: [ConsName]
undocdCommands =
  [ "SetAllContactReceipts",
    "APISetUserContactReceipts",
    "APISetUserGroupReceipts",
    "APIHideUser",
    "APIUnhideUser",
    "APIMuteUser",
    "APIUnmuteUser",
    "StartChat",
    "CheckChatRunning",
    "APIStopChat",
    "APIActivateChat",
    "APISuspendChat",
    "ResubscribeAllConnections",
    "SetTempFolder",
    "SetFilesFolder",
    "SetRemoteHostsFolder",
    "APISetAppFilePaths",
    "APISetEncryptLocalFiles",
    "SetContactMergeEnabled",
    "APIExportArchive",
    "ExportArchive",
    "APIImportArchive",
    "APIDeleteStorage",
    "APIStorageEncryption",
    "TestStorageEncryption",
    "SlowSQLQueries",
    "ExecChatStoreSQL",
    "ExecAgentStoreSQL",
    "APISaveAppSettings",
    "APIGetAppSettings",
    "APIGetChatTags",
    "APICreateChatTag",
    "APISetChatTags",
    "APIDeleteChatTag",
    "APIUpdateChatTag",
    "APIReorderChatTags",
    "APICreateChatItems",
    "APIPlanForwardChatItems",
    "APIForwardChatItems",
    "APIArchiveReceivedReports",
    "APIDeleteReceivedReports",
    "APIUserRead",
    "APISendCallInvitation",
    "APIRejectCall",
    "APISendCallOffer",
    "APISendCallAnswer",
    "APISendCallExtraInfo",
    "APIEndCall",
    "APIGetCallInvitations",
    "APICallStatus",
    "APIGetNetworkStatuses",
    "APISetUserUIThemes",
    "APISetChatUIThemes",
    "APIGetNtfToken",
    "APIRegisterToken",
    "APIVerifyToken",
    "APICheckToken",
    "APIDeleteToken",
    "APIGetNtfConns",
    "APIGetConnNtfMessages",
    "APIAddGroupShortLink",
    "APICreateMemberContact",
    "APISendMemberContactInvitation",
    "GetUserProtoServers",
    "SetUserProtoServers",
    "APITestProtoServer",
    "TestProtoServer",
    "APIGetServerOperators",
    "APISetServerOperators",
    "SetServerOperators",
    "APIGetUserServers",
    "APISetUserServers",
    "APIValidateServers",
    "APIGetUsageConditions",
    "APISetConditionsNotified",
    "APIAcceptConditions",
    "APISetChatItemTTL",
    "SetChatItemTTL",
    "APIGetChatItemTTL",
    "GetChatItemTTL",
    "APISetNetworkConfig",
    "APIGetNetworkConfig",
    "SetNetworkConfig",
    "APISetNetworkInfo",
    "ReconnectAllServers",
    "ReconnectServer",
    "APISetMemberSettings",
    "APIContactInfo",
    "APIGroupInfo",
    "APIGroupMemberInfo",
    "APIContactQueueInfo",
    "APIGroupMemberQueueInfo",
    "APISwitchContact",
    "APISwitchGroupMember",
    "APIAbortSwitchContact",
    "APIAbortSwitchGroupMember",
    "APIEnableContact",
    "APIEnableGroupMember",
    "APIGetContactCode",
    "APIGetGroupMemberCode",
    "APIVerifyContact",
    "APIVerifyGroupMember",
    "APISetConnectionIncognito",
    "APIChangeConnectionUser",
    "APIConnectPlan",
    "APIPrepareContact",
    "APIPrepareGroup",
    "APIChangePreparedContactUser",
    "APIChangePreparedGroupUser",
    "APIConnectPreparedContact",
    "APIConnectPreparedGroup",
    "APIConnectContactViaAddress",
    "APIAddMyAddressShortLink",
    "SetFileToReceive",
    "ListRemoteHosts",
    "StartRemoteHost",
    "SwitchRemoteHost",
    "StopRemoteHost",
    "DeleteRemoteHost",
    "StoreRemoteFile",
    "GetRemoteFile",
    "ConnectRemoteCtrl",
    "FindKnownRemoteCtrl",
    "ConfirmRemoteCtrl",
    "VerifyRemoteCtrlSession",
    "ListRemoteCtrls",
    "StopRemoteCtrl",
    "DeleteRemoteCtrl",
    "APIUploadStandaloneFile",
    "APIDownloadStandaloneFile",
    "APIStandaloneFileInfo",
    "DebugLocks",
    "DebugEvent",
    "GetAgentSubsTotal",
    "GetAgentServersSummary",
    "ResetAgentServersStats",
    "GetAgentSubs",
    "GetAgentSubsDetails",
    "GetAgentWorkers",
    "GetAgentWorkersDetails",
    "GetAgentQueuesInfo",
    "CustomChatCommand"
  ]
