services:
  calculator-bot:
    image: simplex-calculator-bot:latest
    build:
      context: ../..
      dockerfile: scripts/calculator-bot/Dockerfile
    restart: on-failure:5
    # The name must first be registered with the bot address short link.
    # command:
    #   - "--domain"
    #   - "yourname.simplex"
    volumes:
      - calculator-bot-data:/src/apps/simplex-calculator-bot/data

volumes:
  calculator-bot-data:
