*

!cabal.project
!simplex-chat.cabal
!README.md
!PRIVACY.md
!libsimplex.dll.def
!flake.nix
!src
!scripts/cabal.project.local.linux
!scripts/desktop
!packages/simplex-chat-client
!packages/simplex-chat-nodejs
!apps/simplex-calculator-bot

**/node_modules
**/dist
**/build
**/libs
**/data
**/.env
**/.npmrc
